export const CHANGE_AUTHENTICATION_STATE = "CHANGE_AUTHENTICATION_STATE";
export const CHANGE_USER_STATE = "CHANGE_USER_STATE";
export const LOGIN_USER_DATA = "LOGIN_USER_DATA";
export const LOGOUT_USER_DATA = "LOGOUT_USER_DATA";
